SMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler400
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('programs/', include('course.urls')),
    path('result/', include('result.urls')),
    path('search/', include('search.urls')),
    path('quiz/', include('quiz.urls')),

    path('payments/', include('payments.urls')),

    path('accounts/api/', include('accounts.api.urls', namespace='accounts-api')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'app.views.handler404'
# handler500 = 'app.views.handler500'
# handler400 = 'app.views.handler400'

quiz/models.py
import re
import json

from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.core.validators import (MaxValueValidator, validate_comma_separated_integer_list,)
from django.utils.translation import gettext_lazy as _
from django.utils.timezone import now
from django.conf import settings
from django.db.models.signals import pre_save

from django.db.models import Q

from model_utils.managers import InheritanceManager
from course.models import Course
from .utils import *

CHOICE_ORDER_OPTIONS = (
    ('content', _('Content')),
    ('random', _('Random')),
    ('none', _('None'))
)

CATEGORY_OPTIONS = (
    ('assignment', _('Assignment')),
    ('exam', _('Exam')),
    ('practice', _('Practice Quiz'))
)


class QuizManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) | 
                         Q(description__icontains=query)|
                         Q(category__icontains=query)|
                         Q(slug__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class Quiz(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    title = models.CharField(verbose_name=_("Title"), max_length=60, blank=False)
    slug = models.SlugField(blank=True, unique=True)
    description = models.TextField(verbose_name=_("Description"), blank=True, help_text=_("a description of the quiz"))
    category = models.TextField(choices=CATEGORY_OPTIONS, blank=True)
    random_order = models.BooleanField(blank=False, default=False, verbose_name=_("Random Order"), 
        help_text=_("Display the questions in a random order or as they are set?"))

    # max_questions = models.PositiveIntegerField(blank=True, null=True, verbose_name=_("Max Questions"), 
    #     help_text=_("Number of questions to be answered on each attempt."))

    answers_at_end = models.BooleanField(blank=False, default=False, verbose_name=_("Answers at end"),
        help_text=_("Correct answer is NOT shown after question. Answers displayed at the end."))

    exam_paper = models.BooleanField(blank=False, default=False, verbose_name=_("Exam Paper"),
        help_text=_("If yes, the result of each attempt by a user will be stored. Necessary for marking."))

    single_attempt = models.BooleanField(blank=False, default=False, verbose_name=_("Single Attempt"), 
        help_text=_("If yes, only one attempt by a user will be permitted."))

    pass_mark = models.SmallIntegerField(blank=True, default=50, verbose_name=_("Pass Mark"), validators=[MaxValueValidator(100)], 
        help_text=_("Percentage required to pass exam."))

    draft = models.BooleanField(blank=True, default=False, verbose_name=_("Draft"),
        help_text=_("If yes, the quiz is not displayed in the quiz list and can only be taken by users who can edit quizzes."))

    timestamp = models.DateTimeField(auto_now=True)

    objects = QuizManager()

    def save(self, force_insert=False, force_update=False, *args, **kwargs):

        if self.single_attempt is True:
            self.exam_paper = True

        if self.pass_mark > 100:
            raise ValidationError('%s is above 100' % self.pass_mark)
        if self.pass_mark < 0:
            raise ValidationError('%s is below 0' % self.pass_mark)

        super(Quiz, self).save(force_insert, force_update, *args, **kwargs)

    class Meta:
        verbose_name = _("Quiz")
        verbose_name_plural = _("Quizzes")

    def __str__(self):
        return self.title

    def get_questions(self):
        return self.question_set.all().select_subclasses()

    @property
    def get_max_score(self):
        return self.get_questions().count()

    def get_absolute_url(self):
        # return reverse('quiz_start_page', kwargs={'pk': self.pk})
        return reverse('quiz_index', kwargs={'slug': self.course.slug})


def quiz_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(quiz_pre_save_receiver, sender=Quiz)


class ProgressManager(models.Manager):

    def new_progress(self, user):
        new_progress = self.create(user=user, score="")
        new_progress.save()
        return new_progress


class Progress(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)
    score = models.CharField(max_length=1024, verbose_name=_("Score"), validators=[validate_comma_separated_integer_list])

    objects = ProgressManager()

    class Meta:
        verbose_name = _("User Progress")
        verbose_name_plural = _("User progress records")

    # @property
    def list_all_cat_scores(self):
        score_before = self.score
        output = {}

        if len(self.score) > len(score_before):
            # If a new category has been added, save changes.
            self.save()

        return output

    def update_score(self, question, score_to_add=0, possible_to_add=0):
        # category_test = Category.objects.filter(category=question.category).exists()

        if any([item is False for item in [score_to_add, possible_to_add, isinstance(score_to_add, int), isinstance(possible_to_add, int)]]):
            return _("error"), _("category does not exist or invalid score")

        to_find = re.escape(str(question.quiz)) + r",(?P<score>\d+),(?P<possible>\d+),"

        match = re.search(to_find, self.score, re.IGNORECASE)

        if match:
            updated_score = int(match.group('score')) + abs(score_to_add)
            updated_possible = int(match.group('possible')) + abs(possible_to_add)

            new_score = ",".join([str(question.quiz), str(updated_score), str(updated_possible), ""])

            # swap old score for the new one
            self.score = self.score.replace(match.group(), new_score)
            self.save()

        else:
            #  if not present but existing, add with the points passed in
            self.score += ",".join([str(question.quiz), str(score_to_add), str(possible_to_add), ""])
            self.save()

    def show_exams(self):
        if self.user.is_superuser:
            return Sitting.objects.filter(complete=True).order_by('-end')
        else:
            return Sitting.objects.filter(user=self.user, complete=True).order_by('-end')


class SittingManager(models.Manager):

    def new_sitting(self, user, quiz, course):
        if quiz.random_order is True:
            question_set = quiz.question_set.all().select_subclasses().order_by('?')
        else:
            question_set = quiz.question_set.all().select_subclasses()

        question_set = [item.id for item in question_set]

        if len(question_set) == 0:
            raise ImproperlyConfigured('Question set of the quiz is empty. Please configure questions properly')

        # if quiz.max_questions and quiz.max_questions < len(question_set):
        #     question_set = question_set[:quiz.max_questions]

        questions = ",".join(map(str, question_set)) + ","

        new_sitting = self.create(
            user=user, quiz=quiz, course=course, question_order=questions, 
            question_list=questions, incorrect_questions="",
            current_score=0,
            complete=False,
            user_answers='{}'
        )
        return new_sitting

    def user_sitting(self, user, quiz, course):
        if quiz.single_attempt is True and self.filter(user=user, quiz=quiz, course=course, complete=True).exists():
            return False
        try:
            sitting = self.get(user=user, quiz=quiz, course=course, complete=False)
        except Sitting.DoesNotExist:
            sitting = self.new_sitting(user, quiz, course)
        except Sitting.MultipleObjectsReturned:
            sitting = self.filter(user=user, quiz=quiz, course=course, complete=False)[0]
        return sitting


class Sitting(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, verbose_name=_("Quiz"), on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null=True, verbose_name=_("Course"), on_delete=models.CASCADE)

    question_order = models.CharField(max_length=1024, verbose_name=_("Question Order"),
        validators=[validate_comma_separated_integer_list])

    question_list = models.CharField(max_length=1024, verbose_name=_("Question List"),
        validators=[validate_comma_separated_integer_list])

    incorrect_questions = models.CharField(max_length=1024, blank=True, verbose_name=_("Incorrect questions"),
        validators=[validate_comma_separated_integer_list])

    current_score = models.IntegerField(verbose_name=_("Current Score"))
    complete = models.BooleanField(default=False, blank=False, verbose_name=_("Complete"))
    user_answers = models.TextField(blank=True, default='{}', verbose_name=_("User Answers"))
    start = models.DateTimeField(auto_now_add=True, verbose_name=_("Start"))
    end = models.DateTimeField(null=True, blank=True, verbose_name=_("End"))

    objects = SittingManager()

    class Meta:
        permissions = (("view_sittings", _("Can see completed exams.")),)

    def get_first_question(self):
        if not self.question_list:
            return False

        first, _ = self.question_list.split(',', 1)
        question_id = int(first)
        return Question.objects.get_subclass(id=question_id)

    def remove_first_question(self):
        if not self.question_list:
            return

        _, others = self.question_list.split(',', 1)
        self.question_list = others
        self.save()

    def add_to_score(self, points):
        self.current_score += int(points)
        self.save()

    @property

templates/upload/upload_file_form.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}

{% block content %}

<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a>
     <i>&rsaquo;</i> <a href="{% url 'programs' %}" class="primary1">Programs</a> <i>&rsaquo;</i> 
     <a href="{% url 'program_detail' course.program.id %}" class="primary1"> {{ course.program }}</a> <i>&rsaquo;</i> 
     <a href="{% url 'course_detail' course.slug %}" class="primary1">{{ course }}</a>
      <i>&rsaquo;</i> file upload</div>

<p class="title-1">File upload for {{ course }}</p>
<div class="title-line"></div><br>

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">
                <i class="fas fa-exclamation-circle"></i>{{ message }}
            </div>
        {% else %}
            <div class="alert alert-success">
                <i class="fas fa-check-circle"></i>{{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

<div class="row">
<div class="col-md-8 p-0 mx-auto">
    <div class="card">
    <p class="form-title">File Upload Form</p><br>
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="container">
            
            <div class="form-group">
                <b>File Name</b>{{ form.title }}
                <span class="danger">{{ form.title.errors }}</span>
            </div>
            <div class="form-group">
                <b>File</b><br>{{ form.file }}
                <span class="danger">{{ form.file.errors }}</span>
            </div>
            <p class="text-orange"><b>Valid Files: </b>pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip</p>
            <div class="form-group">
                <select hidden name="course" required="" id="id_course">
                    <option value="{{ course.pk }}" selected>{{ course }}</option>
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Upload</button>
                <a class="btn btn-danger" href="{% url 'course_detail' course.slug %}" style="float: right;">Cancel</a>
            </div>

        </div>
        <br>
        <div class="card">
    </form>
</div>
</div>

{% endblock content %}

templates/upload/upload_video_form.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}

{% block content %}

<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a>
     <i>&rsaquo;</i> <a href="{% url 'programs' %}" class="primary1">Programs</a> <i>&rsaquo;</i> 
     <a href="{% url 'program_detail' course.program.id %}" class="primary1"> {{ course.program }}</a> <i>&rsaquo;</i> 
     <a href="{% url 'course_detail' course.slug %}" class="primary1">{{ course }}</a>
      <i>&rsaquo;</i> Video upload</div>

<p class="title-1">Video upload for {{ course }}</p>
<div class="title-line"></div><br>

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">
                <i class="fas fa-exclamation-circle"></i>{{ message }}
            </div>
        {% else %}
            <div class="alert alert-success">
                <i class="fas fa-check-circle"></i>{{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

<div class="row">
<div class="col-md-8 p-0 mx-auto">
    <div class="card">
    <p class="form-title">Video Upload Form</p><br>
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="container">
            
            <div class="form-group">
                <b>Video Name</b>{{ form.title }}
                <span class="danger">{{ form.title.errors }}</span>
            </div>
            <div class="form-group">
                <b>Video</b><br>{{ form.video }}
                <span class="danger">{{ form.video.errors }}</span>
            </div>
            <p class="text-orange"><b>Valid video formats: </b>'mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'</p>
            <div class="form-group">
                <select hidden name="course" required="" id="id_course">
                    <option value="{{ course.pk }}" selected>{{ course }}</option>
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Upload</button>
                <a class="btn btn-danger" href="{% url 'course_detail' course.slug %}" style="float: right;">Cancel</a>
            </div>

        </div>
        <br>
        <div class="card">
    </form>
</div>
</div>

{% endblock content %}

templates/upload/video_single.html
{% extends 'base.html' %}
{% block title %}{{ video.title }} | DjangoSMS{% endblock title %}
{% load static %}

{% block content %}

<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a>
    <i>&rsaquo;</i> <a href="{% url 'programs' %}" class="primary1">Programs</a> <i>&rsaquo;</i> 
    <a href="{% url 'program_detail' video.course.program.id %}" class="primary1"> {{ video.course.program }}</a> <i>&rsaquo;</i> 
    <a href="{% url 'course_detail' video.course.slug %}" class="primary1">{{ video.course }}</a>
     <i>&rsaquo;</i> {{ video.title }}</div>

<p class="title-1">{{ video.title }}</p>
<div class="title-line"></div><br>

<p class="text-orange text-center">Video tutorial for course {{ video.course }}</p>

<style>
    video{
        max-width: 100%; 
        -webkit-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
        box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.16), 0px 2px 10px 0px rgba(0,0,0,0.12);
    }
</style>

<div class="col-md-10 mx-auto d-block">
    <p><i class="fas fa-calendar"></i> {{ video.timestamp|timesince }} ago</p>
    <div class=""><video src="{{ video.video.url }}" controls ></video></div>
</div>

<p class="text-orange text-center">{{ video.summary }}</p>

{% endblock content %}