SMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler400
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('programs/', include('course.urls')),
    path('result/', include('result.urls')),
    path('search/', include('search.urls')),
    path('quiz/', include('quiz.urls')),

    path('payments/', include('payments.urls')),

    path('accounts/api/', include('accounts.api.urls', namespace='accounts-api')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'app.views.handler404'
# handler500 = 'app.views.handler500'
# handler400 = 'app.views.handler400'

quiz/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('<slug>/quizzes/', quiz_list, name='quiz_index'),

    path('progress/', view=QuizUserProgressView.as_view(), name='quiz_progress'),

    # path('marking/<int:pk>/', view=QuizMarkingList.as_view(), name='quiz_marking'),
    path('marking_list/', view=QuizMarkingList.as_view(), name='quiz_marking'),

    path('marking/<int:pk>/', view=QuizMarkingDetail.as_view(), name='quiz_marking_detail'),

    path('<int:pk>/<slug>/take/', view=QuizTake.as_view(), name='quiz_take'),

    path('<slug>/quiz_add/', QuizCreateView.as_view(), name='quiz_create'),
    path('<slug>/<int:pk>/add/', QuizUpdateView.as_view(), name='quiz_update'),
    path('<slug>/<int:pk>/delete/', quiz_delete, name='quiz_delete'),
    path('mc-question/add/<slug>/<int:quiz_id>/', MCQuestionCreate.as_view(), name='mc_create'),
    # path('mc-question/add/<int:pk>/<quiz_pk>/', MCQuestionCreate.as_view(), name='mc_create'),
]

quiz/models.py
import re
import json

from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.core.validators import (MaxValueValidator, validate_comma_separated_integer_list,)
from django.utils.translation import gettext_lazy as _
from django.utils.timezone import now
from django.conf import settings
from django.db.models.signals import pre_save

from django.db.models import Q

from model_utils.managers import InheritanceManager
from course.models import Course
from .utils import *

CHOICE_ORDER_OPTIONS = (
    ('content', _('Content')),
    ('random', _('Random')),
    ('none', _('None'))
)

CATEGORY_OPTIONS = (
    ('assignment', _('Assignment')),
    ('exam', _('Exam')),
    ('practice', _('Practice Quiz'))
)


class QuizManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) | 
                         Q(description__icontains=query)|
                         Q(category__icontains=query)|
                         Q(slug__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class Quiz(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    title = models.CharField(verbose_name=_("Title"), max_length=60, blank=False)
    slug = models.SlugField(blank=True, unique=True)
    description = models.TextField(verbose_name=_("Description"), blank=True, help_text=_("a description of the quiz"))
    category = models.TextField(choices=CATEGORY_OPTIONS, blank=True)
    random_order = models.BooleanField(blank=False, default=False, verbose_name=_("Random Order"), 
        help_text=_("Display the questions in a random order or as they are set?"))

    # max_questions = models.PositiveIntegerField(blank=True, null=True, verbose_name=_("Max Questions"), 
    #     help_text=_("Number of questions to be answered on each attempt."))

    answers_at_end = models.BooleanField(blank=False, default=False, verbose_name=_("Answers at end"),
        help_text=_("Correct answer is NOT shown after question. Answers displayed at the end."))

    exam_paper = models.BooleanField(blank=False, default=False, verbose_name=_("Exam Paper"),
        help_text=_("If yes, the result of each attempt by a user will be stored. Necessary for marking."))

    single_attempt = models.BooleanField(blank=False, default=False, verbose_name=_("Single Attempt"), 
        help_text=_("If yes, only one attempt by a user will be permitted."))

    pass_mark = models.SmallIntegerField(blank=True, default=50, verbose_name=_("Pass Mark"), validators=[MaxValueValidator(100)], 
        help_text=_("Percentage required to pass exam."))

    draft = models.BooleanField(blank=True, default=False, verbose_name=_("Draft"),
        help_text=_("If yes, the quiz is not displayed in the quiz list and can only be taken by users who can edit quizzes."))

    timestamp = models.DateTimeField(auto_now=True)

    objects = QuizManager()

    def save(self, force_insert=False, force_update=False, *args, **kwargs):

        if self.single_attempt is True:
            self.exam_paper = True

        if self.pass_mark > 100:
            raise ValidationError('%s is above 100' % self.pass_mark)
        if self.pass_mark < 0:
            raise ValidationError('%s is below 0' % self.pass_mark)

        super(Quiz, self).save(force_insert, force_update, *args, **kwargs)

    class Meta:
        verbose_name = _("Quiz")
        verbose_name_plural = _("Quizzes")

    def __str__(self):
        return self.title

    def get_questions(self):
        return self.question_set.all().select_subclasses()

    @property
    def get_max_score(self):
        return self.get_questions().count()

    def get_absolute_url(self):
        # return reverse('quiz_start_page', kwargs={'pk': self.pk})
        return reverse('quiz_index', kwargs={'slug': self.course.slug})


def quiz_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(quiz_pre_save_receiver, sender=Quiz)


class ProgressManager(models.Manager):

    def new_progress(self, user):
        new_progress = self.create(user=user, score="")
        new_progress.save()
        return new_progress


class Progress(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)
    score = models.CharField(max_length=1024, verbose_name=_("Score"), validators=[validate_comma_separated_integer_list])

    objects = ProgressManager()

    class Meta:
        verbose_name = _("User Progress")
        verbose_name_plural = _("User progress records")

    # @property
    def list_all_cat_scores(self):
        score_before = self.score
        output = {}

        if len(self.score) > len(score_before):
            # If a new category has been added, save changes.
            self.save()

        return output

    def update_score(self, question, score_to_add=0, possible_to_add=0):
        # category_test = Category.objects.filter(category=question.category).exists()

        if any([item is False for item in [score_to_add, possible_to_add, isinstance(score_to_add, int), isinstance(possible_to_add, int)]]):
            return _("error"), _("category does not exist or invalid score")

        to_find = re.escape(str(question.quiz)) + r",(?P<score>\d+),(?P<possible>\d+),"

        match = re.search(to_find, self.score, re.IGNORECASE)

        if match:
            updated_score = int(match.group('score')) + abs(score_to_add)
            updated_possible = int(match.group('possible')) + abs(possible_to_add)

            new_score = ",".join([str(question.quiz), str(updated_score), str(updated_possible), ""])

            # swap old score for the new one
            self.score = self.score.replace(match.group(), new_score)
            self.save()

        else:
            #  if not present but existing, add with the points passed in
            self.score += ",".join([str(question.quiz), str(score_to_add), str(possible_to_add), ""])
            self.save()

    def show_exams(self):
        if self.user.is_superuser:
            return Sitting.objects.filter(complete=True).order_by('-end')
        else:
            return Sitting.objects.filter(user=self.user, complete=True).order_by('-end')


class SittingManager(models.Manager):

    def new_sitting(self, user, quiz, course):
        if quiz.random_order is True:
            question_set = quiz.question_set.all().select_subclasses().order_by('?')
        else:
            question_set = quiz.question_set.all().select_subclasses()

        question_set = [item.id for item in question_set]

        if len(question_set) == 0:
            raise ImproperlyConfigured('Question set of the quiz is empty. Please configure questions properly')

        # if quiz.max_questions and quiz.max_questions < len(question_set):
        #     question_set = question_set[:quiz.max_questions]

        questions = ",".join(map(str, question_set)) + ","

        new_sitting = self.create(
            user=user, quiz=quiz, course=course, question_order=questions, 
            question_list=questions, incorrect_questions="",
            current_score=0,
            complete=False,
            user_answers='{}'
        )
        return new_sitting

    def user_sitting(self, user, quiz, course):
        if quiz.single_attempt is True and self.filter(user=user, quiz=quiz, course=course, complete=True).exists():
            return False
        try:
            sitting = self.get(user=user, quiz=quiz, course=course, complete=False)
        except Sitting.DoesNotExist:
            sitting = self.new_sitting(user, quiz, course)
        except Sitting.MultipleObjectsReturned:
            sitting = self.filter(user=user, quiz=quiz, course=course, complete=False)[0]
        return sitting


class Sitting(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, verbose_name=_("Quiz"), on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null=True, verbose_name=_("Course"), on_delete=models.CASCADE)

    question_order = models.CharField(max_length=1024, verbose_name=_("Question Order"),
        validators=[validate_comma_separated_integer_list])

    question_list = models.CharField(max_length=1024, verbose_name=_("Question List"),
        validators=[validate_comma_separated_integer_list])

    incorrect_questions = models.CharField(max_length=1024, blank=True, verbose_name=_("Incorrect questions"),
        validators=[validate_comma_separated_integer_list])

    current_score = models.IntegerField(verbose_name=_("Current Score"))
    complete = models.BooleanField(default=False, blank=False, verbose_name=_("Complete"))
    user_answers = models.TextField(blank=True, default='{}', verbose_name=_("User Answers"))
    start = models.DateTimeField(auto_now_add=True, verbose_name=_("Start"))
    end = models.DateTimeField(null=True, blank=True, verbose_name=_("End"))

    objects = SittingManager()

    class Meta:
        permissions = (("view_sittings", _("Can see completed exams.")),)

    def get_first_question(self):
        if not self.question_list:
            return False

        first, _ = self.question_list.split(',', 1)
        question_id = int(first)
        return Question.objects.get_subclass(id=question_id)

    def remove_first_question(self):
        if not self.question_list:
            return

        _, others = self.question_list.split(',', 1)
        self.question_list = others
        self.save()

    def add_to_score(self, points):
        self.current_score += int(points)
        self.save()

    @property

quiz/forms.py
from django import forms
from django.forms.widgets import RadioSelect, Textarea
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.utils.translation import gettext_lazy as _
from django.db import transaction

from django.forms.models import inlineformset_factory

from accounts.models import User
from .models import Question, Quiz, MCQuestion, Choice


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_choices_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choice_list, widget=RadioSelect)


class EssayForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(EssayForm, self).__init__(*args, **kwargs)
        self.fields["answers"] = forms.CharField(
            widget=Textarea(attrs={'style': 'width:100%'}))


class QuizAddForm(forms.ModelForm):

    class Meta:
        model = Quiz
        exclude = []

    questions = forms.ModelMultipleChoiceField(
        queryset=Question.objects.all().select_subclasses(),
        required=False,
        label=_("Questions"),
        widget=FilteredSelectMultiple(
            verbose_name=_("Questions"),
            is_stacked=False))

    def __init__(self, *args, **kwargs):
        super(QuizAddForm, self).__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['questions'].initial = self.instance.question_set.all().select_subclasses()

    def save(self, commit=True):
        quiz = super(QuizAddForm, self).save(commit=False)
        quiz.save()
        quiz.question_set.set(self.cleaned_data['questions'])
        self.save_m2m()
        return quiz


class MCQuestionForm(forms.ModelForm):

    class Meta:
        model = MCQuestion
        exclude = ()


MCQuestionFormSet = inlineformset_factory(
    MCQuestion, Choice, form=MCQuestionForm, fields=['choice', 'correct'], can_delete=True, extra=5
)

templates/quiz/quiz_form.html
{% extends 'base.html' %}

{% block content %}

<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i> 
    <a href="{% url 'programs' %}" class="primary1"> Programs</a> <i>&rsaquo;</i> 
    <a href="{% url 'program_detail' course.program.id %}" class="primary1"> {{ course.program }}</a> <i>&rsaquo;</i> 
    <a href="{{ course.get_absolute_url }}" class="primary1">{{ course }}</a> <i>&rsaquo;</i> 
    <a href="{% url 'quiz_index' course.slug %}" class="primary1">Quizzes</a> <i>&rsaquo;</i> Add Quiz</div>

<div class="container">
    <div class="header-title-xl text-center">Quiz form for {{ course }}</div>
    <div class="title-line mb-5"></div>

    <!-- <form method="POST" action="">{% csrf_token %}
        <div class="card p-4">
            {% for f in form %}
            <label for="{{ f.label }}">{{ f.label }}</label>{{ f }}
            {% endfor %}
            <button class="btn btn-primary" type="submit">Save</button>
        </div>
    </form> -->
    <!-- <form action="" method="POST">{% csrf_token %}
        <div class="row">
            <div class="col mx-3 p-3 bg-white">
                <div class="container">
                    <div class="form-group">
                        <label for="course">{{ form.course.label }}</label> {{ form.course }}
                        <span class="danger">{{ form.course.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="title">{{ form.title.label }}</label> {{ form.title }}
                        <span class="danger">{{ form.title.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="category">{{ form.category.label }}</label> {{ form.category }}
                        <span class="danger">{{ form.category.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="max_questions">{{ form.max_questions.label }}</label> {{ form.max_questions }}
                        <span class="danger">{{ form.max_questions.errors }}</span>
                        <small class="d-block text-muted">Number of questions to be answered on each attempt.</small>
                    </div>
                    <div class="form-group">
                        <label for="pass_mark">{{ form.pass_mark.label }}</label> {{ form.pass_mark }}
                        <span class="danger">{{ form.pass_mark.errors }}</span>
                        <small class="d-block text-muted">Percentage required to pass exam.</small>
                    </div>
                    <div class="form-group">
                        <label for="description">{{ form.description.label }}</label> {{ form.description }}
                        <span class="danger">{{ form.description.errors }}</span>
                        <small class="d-block text-muted">a description of the quiz</small>
                    </div>
                </div>
            </div>
            <div class="col mx-3 p-3 bg-white">
                <div class="container">
                    <div class="form-group">
                        <label for="questions">{{ form.questions.label }}</label> {{ form.questions }}
                        <span class="danger">{{ form.questions.errors }}</span>
                        <small class="d-block text-muted">Hold down "Control", or "Command" on a Mac, to select more than one.</small>
                    </div>
                    <div class="form-group">
                        <label for="random_order">{{ form.random_order.label }}</label> {{ form.random_order }}
                        <span class="danger">{{ form.random_order.errors }}</span>
                        <small class="d-block text-muted">Display the questions in a random order or as they are set?</small>
                    </div>
                    <div class="form-group">
                        <label for="answers_at_end">{{ form.answers_at_end.label }}</label> {{ form.answers_at_end }}
                        <span class="danger">{{ form.answers_at_end.errors }}</span>
                        <small class="d-block text-muted">Correct answer is NOT shown after question. Answers displayed at the end.</small>
                    </div>
                    <div class="form-group">
                        <label for="exam_paper">{{ form.exam_paper.label }}</label> {{ form.exam_paper }}
                        <span class="danger">{{ form.exam_paper.errors }}</span>
                        <small class="d-block text-muted">If yes, the result of each attempt by a user will be stored. Necessary for marking.</small>
                    </div>
                    <div class="form-group">
                        <label for="single_attempt">{{ form.single_attempt.label }}</label> {{ form.single_attempt }}
                        <span class="danger">{{ form.single_attempt.errors }}</span>
                        <small class="d-block text-muted">If yes, only one attempt by a user will be permitted. Non users cannot sit this exam.</small>
                    </div>
                    <div class="form-group">
                        <label for="draft">{{ form.draft.label }}</label> {{ form.draft }}
                        <span class="danger">{{ form.draft.errors }}</span>
                        <small class="d-block text-muted">If yes, the quiz is not displayed in the quiz list and can only be taken by users who can edit quizzes.</small>
                    </div>
                </div>
            </div>
        </div>
        <center>
            <button class="btn btn-primary my-4" type="submit">Save & Continue</button>
        </center>
    </form> -->

    <form action="" method="POST">{% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <div class="card p-2">
                <!-- <div class="container"> -->
                    <div class="form-group" hidden>
                        <label for="course">{{ form.course.label }}</label><br> {{ form.course }}
                        <span class="danger">{{ form.course.errors }}</span>
                        <span class="danger">{{ form.course.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="category">{{ form.category.label }}</label> {{ form.category }}
                        <span class="danger">{{ form.category.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="title">{{ form.title.label }}</label>
                        {{ form.title }}
                        <!-- <input type="text" name="title" value="{{ form.title }}" maxlength="60" required id="id_title" class="form-control"> -->
                    </div>
                    <!-- <div class="form-group">
                        <label for="max_questions">{{ form.max_questions.label }}</label>
                        <input class="form-control" type="number" name="max_questions" min="0" id="id_max_questions">
                        <span class="danger">{{ form.max_questions.errors }}</span>
                        <small class="d-block text-muted">Number of questions to be answered on each attempt.</small>
                    </div> -->
                    <div class="form-group">
                        <label for="pass_mark">{{ form.pass_mark.label }}</label>
                        {{ form.pass_mark }}
                        <!-- <input class="form-control" type="number" name="pass_mark" value="50" id="id_pass_mark"> -->
                        <span class="danger">{{ form.pass_mark.errors }}</span>
                        <small class="d-block text-muted">Percentage required to pass exam.</small>
                    </div>
                    <div class="form-group">
                        <label for="description">{{ form.description.label }}</label><br>
                        {{ form.description }}
                        <!-- <textarea name="description" class="form-control" id="id_description"></textarea> -->
                        <span class="danger">{{ form.description.errors }}</span>
                        <small class="d-block text-muted">a description of the quiz</small>
                    </div>
                <!-- </div> -->
                </div>
            </div>
            <div class="col-md-6">
                <div class="card p-3">
                <!-- <div class="container"> -->
                    <div class="form-group" hidden>
                        <label for="questions">{{ form.questions.label }}</label><br> {{ form.questions }}
                        <span class="danger">{{ form.questions.errors }}</span>
                        <small class="d-block text-muted">Hold down "Control", or "Command" on a Mac, to select more than one.</small>
                    </div>
                    <div class="form-group">
                        <label for="random_order">{{ form.random_order.label }}</label>
                        {{ form.random_order }}
                        <!-- <input class="custom-checkbox" type="checkbox" name="random_order" id="id_random_order"> -->
                        <span class="danger">{{ form.random_order.errors }}</span>
                        <small class="d-block text-muted">Display the questions in a random order or as they are set?</small>
                    </div>
                    <div class="form-group">
                        <label for="answers_at_end">{{ form.answers_at_end.label }}</label>
                        {{ form.answers_at_end }}
                        <!-- <input class="custom-checkbox" type="checkbox" name="answers_at_end" id="id_answers_at_end"> -->
                        <span class="danger">{{ form.answers_at_end.errors }}</span>
                        <small class="d-block text-muted">Correct answer is NOT shown after question. Answers displayed at the end.</small>
                    </div>
                    <div class="form-group">
                        <label for="exam_paper">{{ form.exam_paper.label }}</label>
                        {{ form.exam_paper }}
                        <!-- <input class="custom-checkbox" type="checkbox" name="exam_paper" id="id_exam_paper"> -->
                        <span class="danger">{{ form.exam_paper.errors }}</span>
                        <small class="d-block text-muted">If yes, the result of each attempt by a user will be stored. Necessary for marking.</small>
                    </div>
                    <div class="form-group">
                        <label for="single_attempt">{{ form.single_attempt.label }}</label>
                        {{ form.single_attempt }}
                        <!-- <input class="custom-checkbox" type="checkbox" name="single_attempt" id="id_single_attempt"> -->
                        <span class="danger">{{ form.single_attempt.errors }}</span>
                        <small class="d-block text-muted">If yes, only one attempt by a user will be permitted. Non users cannot sit this exam.</small>
                    </div>
                    <div class="form-group">
                        <label for="draft">{{ form.draft.label }}</label>
                        {{ form.draft }}
                        <!-- <input class="custom-checkbox" type="checkbox" name="draft" id="id_draft"> -->
                        <span class="danger">{{ form.draft.errors }}</span>
                        <small class="d-block text-muted">If yes, the quiz is not displayed in the quiz list and can only be taken by users who can edit quizzes.</small>
                    </div>
                <!-- </div> -->
                </div>
            </div>
        </div>
        <center>
            <button class="btn btn-lg btn-primary my-4" id="{% if form.is_valid %}btn-transition{% endif %}" type="submit">Save & Continue</button>
        </center>
    </form>
</div>

{% endblock %}

{% block js %}
<script>
    const transitionButton = document.getElementById('btn-transition');
    transitionButton.addEventListener('click', () => {
        document.getElementById('card-transition').style.animation = 'card-transition 5s ease-in-out forwards';
    })
</script>
{% endblock js %}

templates/quiz/quiz_list.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load i18n %}
{% load static %}

{% block content %}

<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i> 
    <a href="{% url 'programs' %}" class="primary1"> Programs</a> <i>&rsaquo;</i> 
    <a href="{% url 'program_detail' pk=1 %}" class="primary1"> {{ course.program }}</a> <i>&rsaquo;</i> 
    <a href="{{ course.get_absolute_url }}" class="primary1"> {{ course }}</a> <i>&rsaquo;</i> Quiz List</div>

<div class="container">

    {% if messages %}
        <div id="popup-box-messages">
            <div class="box-messages">
                <a id="popup-btn-messages" class="btn btn-light"><i class="fas fa-times"></i></a><br><br>
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <style>.bg-light-warning{background-color: rgb(252, 217, 111) !important;}</style>

    <div class="header-title-xl text-center">Quiz list of {{ course }}</div>
    <div class="title-line mb-5"></div>

    {% if request.user.is_superuser or request.user.is_lecturer %}
    <a class="btn btn-outline-primary br-2 mb-4" href="{% url 'quiz_create' course.slug %}">&plus; Add Quiz</a>
    {% endif %}

    <div class="row">
        {% for quiz in quizzes %}
        <div class="col-md-4 mb-4 mx-auto text-center">
            <div class="card p-2 quiz-wrapper">
                {% if request.user.is_superuser or request.user.is_lecturer %}
                <div class="update-delete-wrapper">
                    <div class="navbar">
                        <li class="dropdown">
                            <a class="dropdown-toggle-split" href="#" id="dropdown01" data-toggle="dropdown"><i class="fas fa-ellipsis-v text-white"></i></a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">
                                <a href="{% url 'quiz_update' slug=course.slug pk=quiz.id %}" class="update"><i class="fas fa-pencil-alt"></i> Edit</a>
                                <a href="{% url 'quiz_delete' slug=course.slug pk=quiz.id %}" class="delete"><i class="fas fa-trash-alt"></i> Delete</a>
                            </div>
                        </li>
                    </div>
                </div>
                {% endif %}
                <div class="row text-success mb-4">
                    <em class="col-6 text-left">{{ quiz.category|title }} Quiz</em>
                    <div class="col-6 text-right info-text bg-danger" style="border-bottom-right-radius: 1px; border-top-right-radius: 1px;">
                        {{ quiz.get_questions.count }} Questions
                    </div>
                </div>
                <!-- <p>{{ quiz.category|title }} Quiz</p> -->
                <div class="card-title header-title-md">{{ quiz.title|title }}</div>
                <!-- <div class="col-md-4 info-text bg-danger" style="float: right; width: auto;">
                    {{ quiz.get_questions.count }} Questions
                </div> -->
                {% if quiz.single_attempt %}
                <p class="p-2 bg-light-warning">{% trans "You will only get one attempt at this quiz" %}.</p>
                {% endif %}
                <p class="text-muted">{{ quiz.description }} here is the description of this quiz...</p>
                <!-- <p class="lead">{{ quiz.get_questions.count }} Questions</p> -->
                <!-- <div class="row text-success mb-4">
                    <small class="col-6 text-left">{% trans "Category" %}: <b>{{ quiz.category }}</b></small>
                    <small class="col-6 text-right">Time set: <b>1:30</b></small>
                </div> -->
                <a class="btn btn-block btn-secondary" href="{% url 'quiz_take' pk=course.pk slug=quiz.slug %}">{% trans "Start quiz" %} &raquo;</a>
            </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
        {% endfor %}
    </div>

</div>
{% endblock %}

{% block js %}
<script>
    // #####################################
    // loader
    // document.getElementById('progress-main').style.display = 'none';
    var timer = setInterval(function(){
        document.getElementById('progress-card').style.display = 'none';
        document.getElementById('progress-main').style.display = 'block';
        clearInterval(timer)
    }, 8000);           
</script>
{% endblock js %}